#!/usr/bin/python

# Check if there is a 'fail' test case on input
#
# Copyright (C) 2016 Intel Corporation
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

import fileinput
from sys import exit
from json import loads

def any_fail(jsonlines):
    for jsonline in fileinput.input('-'):
        result = loads(jsonline)
	if result['status'] == 'FAIL':
           break
    else:
        # all results either pass or skip
        return "no"
    return "yes"

if __name__ == '__main__':
    ret = 1
    try:
        print any_fail(fileinput.input('-'))
        ret = 0
    except:
        import traceback
        traceback.print_exc(5)
    exit(ret)

