#!/usr/bin/env python

# Produce a summary based on input (--json) results coming from patchtest
#
# Copyright (C) 2016 Intel Corporation
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

import sys
from os.path import join, dirname, realpath
from os import environ
import fileinput
from json import loads
from argparse import ArgumentParser
from jinja2 import Environment, FileSystemLoader

THISDIR = environ['PTOE'] + '/scripts'
env = Environment(loader=FileSystemLoader(THISDIR))
template = env.get_template('summary.j2')

def summary(stdin, series='', revision=''):
    results_list = []
    for line in stdin:
        result  = loads(line)
        status  = result['status']
        results = result['results']
        if not 'pretest' in results[0][1]:
           results_list.append(results)
    output_from_parsed_template = template.render(series_id = series, revision_number = revision, pt_results = results_list)
    print output_from_parsed_template
if __name__ == '__main__':
    parser = ArgumentParser(description="Create a summary")
    parser.add_argument('series',    help='Poll series since the specify date')
    parser.add_argument('revision',  help='Repository directory')
    args = parser.parse_args()

    ret = 1
    try:
        stdin = fileinput.input('-')
        ret = summary(stdin, args.series, args.revision)
    except:
        import traceback
        traceback.print_exc(5)
    sys.exit(ret)
