#!/usr/bin/env python

import fileinput
from sys import exit
from json import loads

def any_fail(jsonlines):
    for jsonline in fileinput.input('-'):
        result = loads(jsonline)
	if result['status'] == 'FAIL':
           break
    else:
        # all results either pass or skip
        return "no"
    return "yes"

if __name__ == '__main__':
    ret = 1
    try:
        print any_fail(fileinput.input('-'))
        ret = 0
    except:
        import traceback
        traceback.print_exc(5)
    exit(ret)

